/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerCidade;
import Controller.ControllerSeguradoraCidadeEstado;
import Controller.ControllerEstado;
import Controller.ControllerSeguradora;
import DAO.DAOSeguradora;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.ModelSeguradora;
import Model.ModelSeguradoraCidadeEstado;
import java.awt.Toolkit;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import util.Exporter;

/**
 *
 * @author studiomicroweb
 */
public final class ViewSeguradora extends javax.swing.JFrame {

    ArrayList<ModelSeguradoraCidadeEstado> listaModelSeguradoraCidadeEstados = new ArrayList<>();
    ControllerSeguradoraCidadeEstado controllerSeguradoraCidadeEstado = new ControllerSeguradoraCidadeEstado();
    ControllerSeguradora controllerSeguradora = new ControllerSeguradora(); // excluir
    ModelSeguradora modelSeguradora = new ModelSeguradora();

    /*Box Cidade e Estado */
    ControllerCidade controllerCidade = new ControllerCidade();
    ControllerEstado controllerEstado = new ControllerEstado();

    /*Pesquisar*/
    List<ModelSeguradora> listaseguradora = new ArrayList<>();
    DAOSeguradora seguradoraDAO = new DAOSeguradora();

    /**
     * Creates new form ViewSeguradora
     */
    public ViewSeguradora() {
        initComponents();
        SetIcone();
        this.carregarSeguradoras();
        setLocationRelativeTo(null);
    }
    static int codigo = 0;
    static String tipoCadastro = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSeguradora().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        tfPesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        cbPesquisa = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbSeguradora = new javax.swing.JTable();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jbVisualizarConta = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();

        setMinimumSize(new java.awt.Dimension(1187, 600));
        setPreferredSize(new java.awt.Dimension(1187, 600));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btIncluir.setBackground(new java.awt.Color(0, 153, 0));
        btIncluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btIncluir.setForeground(new java.awt.Color(255, 255, 255));
        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_add.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        jPanel2.add(btIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 30));

        btEditar.setBackground(new java.awt.Color(255, 102, 0));
        btEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditar.setForeground(new java.awt.Color(255, 255, 255));
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_edit.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 120, 30));

        btExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_delete.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 120, 30));

        tfPesquisa.setPreferredSize(new java.awt.Dimension(6, 25));
        tfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaActionPerformed(evt);
            }
        });
        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyPressed(evt);
            }
        });
        jPanel2.add(tfPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 350, 30));

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(51, 51, 51));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Find.png"))); // NOI18N
        btPesquisar.setText("BUSCAR");
        btPesquisar.setPreferredSize(new java.awt.Dimension(120, 30));
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 120, 30));

        cbPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbPesquisa.setForeground(new java.awt.Color(51, 51, 51));
        cbPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Nome", "Cnpj", "Cidade" }));
        cbPesquisa.setPreferredSize(new java.awt.Dimension(68, 25));
        jPanel2.add(cbPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 80, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SEGURADORAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(251, 251, 251));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/seguradoras.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jScrollPane7.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane7.setPreferredSize(new java.awt.Dimension(1170, 170));

        tbSeguradora.setAutoCreateRowSorter(true);
        tbSeguradora.setBackground(new java.awt.Color(247, 247, 247));
        tbSeguradora.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbSeguradora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Nome", "CNPJ", "Cidade", "UF", "Telefone", "Celular", "Email", "Observações"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSeguradora.setGridColor(new java.awt.Color(247, 247, 247));
        tbSeguradora.setMinimumSize(new java.awt.Dimension(610, 0));
        tbSeguradora.setRowHeight(20);
        tbSeguradora.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbSeguradora.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(tbSeguradora);
        if (tbSeguradora.getColumnModel().getColumnCount() > 0) {
            tbSeguradora.getColumnModel().getColumn(0).setMinWidth(0);
            tbSeguradora.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbSeguradora.getColumnModel().getColumn(0).setMaxWidth(0);
            tbSeguradora.getColumnModel().getColumn(1).setMinWidth(200);
            tbSeguradora.getColumnModel().getColumn(2).setMinWidth(100);
            tbSeguradora.getColumnModel().getColumn(3).setMinWidth(100);
            tbSeguradora.getColumnModel().getColumn(4).setMinWidth(50);
            tbSeguradora.getColumnModel().getColumn(5).setMinWidth(100);
            tbSeguradora.getColumnModel().getColumn(6).setMinWidth(100);
            tbSeguradora.getColumnModel().getColumn(7).setMinWidth(150);
        }

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 1100, 340));

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(234, 239, 243));
        kGradientPanel1.setkGradientFocus(-5);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(520, 210));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbVisualizarConta.setBackground(new java.awt.Color(0, 153, 0));
        jbVisualizarConta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbVisualizarConta.setForeground(new java.awt.Color(255, 255, 255));
        jbVisualizarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/excel.png"))); // NOI18N
        jbVisualizarConta.setText("EXPORTAR");
        jbVisualizarConta.setPreferredSize(new java.awt.Dimension(150, 40));
        jbVisualizarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarContaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jbVisualizarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, -1, -1));

        jPanel2.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1190, 300));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_refresh.png"))); // NOI18N
        jButton8.setPreferredSize(new java.awt.Dimension(60, 40));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, -1, -1));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(234, 239, 243));
        kGradientPanel2.setkGradientFocus(0);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1190, 70));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        // TODO add your handling code here:
        tipoCadastro = "novo";
        new ViewCadSeguradora().setVisible(true);
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        tipoCadastro = "alteracao";

        int linha = tbSeguradora.getSelectedRow();
        String nome = (String) tbSeguradora.getValueAt(linha, 1);
        codigo = (int) tbSeguradora.getValueAt(linha, 0);

        modelSeguradora = controllerSeguradora.getSeguradoraController(codigo);
        if (modelSeguradora != null) {
            new ViewCadSeguradora().setVisible(true);
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tbSeguradora.getSelectedRow();
        String nome = (String) tbSeguradora.getValueAt(linha, 1);
        int codigo = (int) tbSeguradora.getValueAt(linha, 0);

        //Pergunta se realmente deseja exclir
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                + "excluir o registro:\n " + "\n" + nome + "?", "Atenção", JOptionPane.YES_NO_OPTION);
        // se sim exclui, se nao nao faz nada
        if (opcao == JOptionPane.OK_OPTION) {
            if (controllerSeguradora.excluirSeguradoraController(codigo)) {
                JOptionPane.showMessageDialog(this, "Registro excluido com sucesso!");
                carregarSeguradoras();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao e os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        carregarSeguradoras();
    }//GEN-LAST:event_formFocusGained

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        String seleciona = "";
        String conteudo = tfPesquisa.getText();
        int i = cbPesquisa.getSelectedIndex();
        switch (i) {
            case 0:
                seleciona = "seguradoras.codigo";
                break;
            case 1:
                seleciona = "seguradoras.nome";
                break;
            case 2:
                seleciona = "seguradoras.cnpj";
                break;
            case 3:
                seleciona = "cidade.nome";
                break;
            default:
                System.out.println("Não selecionado");
                break;
        }
        try {
            listaModelSeguradoraCidadeEstados = controllerSeguradoraCidadeEstado.pesquisaListaSeguradoraCidadeEstadoController(seleciona, conteudo);
            pesquisa(listaModelSeguradoraCidadeEstados);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Conteúdo não encontrado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Erro ao listar os produtos: " + ex.getMessage());
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.carregarSeguradoras();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbVisualizarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarContaActionPerformed

        if (tbSeguradora.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List<JTable> tb = new ArrayList<JTable>();
                List<String> nom = new ArrayList<String>();
                tb.add(tbSeguradora);
                nom.add("Personas");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Os dados foram exportados com sucesso!", "ARQUIVO EXCEL", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un error " + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há dados para exportar na tabela", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbVisualizarContaActionPerformed

    private void tfPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String seleciona = "";
            String conteudo = tfPesquisa.getText();
            int i = cbPesquisa.getSelectedIndex();
            switch (i) {
                case 0:
                    seleciona = "seguradoras.codigo";
                    break;
                case 1:
                    seleciona = "seguradoras.nome";
                    break;
                case 2:
                    seleciona = "seguradoras.cnpj";
                    break;
                case 3:
                    seleciona = "cidade.nome";
                    break;
                default:
                    System.out.println("Não selecionado");
                    break;
            }
            try {
                listaModelSeguradoraCidadeEstados = controllerSeguradoraCidadeEstado.pesquisaListaSeguradoraCidadeEstadoController(seleciona, conteudo);
                pesquisa(listaModelSeguradoraCidadeEstados);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Conteúdo não encontrado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Erro ao listar os produtos: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tfPesquisaKeyPressed

    public void carregarSeguradoras() {

        listaModelSeguradoraCidadeEstados = controllerSeguradoraCidadeEstado.getlistaSeguradoraCidadeEstadosController();
        DefaultTableModel modelo = (DefaultTableModel) tbSeguradora.getModel();
        modelo.setNumRows(0);
        //Carrega os dados da lista na tabela
        int cont = listaModelSeguradoraCidadeEstados.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelSeguradoraCidadeEstados.get(i).getModelSeguradora().getCodigo(),
                listaModelSeguradoraCidadeEstados.get(i).getModelSeguradora().getNome(),
                listaModelSeguradoraCidadeEstados.get(i).getModelSeguradora().getCnpj(),
                listaModelSeguradoraCidadeEstados.get(i).getModelCidade().getNome(),
                listaModelSeguradoraCidadeEstados.get(i).getModelEstado().getUf(),
                listaModelSeguradoraCidadeEstados.get(i).getModelSeguradora().getTelefone(),
                listaModelSeguradoraCidadeEstados.get(i).getModelSeguradora().getCelular(),
                listaModelSeguradoraCidadeEstados.get(i).getModelSeguradora().getEmail(),
                listaModelSeguradoraCidadeEstados.get(i).getModelSeguradora().getObservacao(),});

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbPesquisa;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton jbVisualizarConta;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTable tbSeguradora;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables

//carregamento de arquivo após atualizar
    public static ViewSeguradora seguradora;

    private void pesquisa(ArrayList<ModelSeguradoraCidadeEstado> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tbSeguradora.getModel();
        modelo.setNumRows(0);

        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = lista.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                lista.get(i).getModelSeguradora().getCodigo(),
                lista.get(i).getModelSeguradora().getNome(),
                lista.get(i).getModelSeguradora().getCnpj(),
                lista.get(i).getModelCidade().getNome(),
                lista.get(i).getModelEstado().getUf(),
                lista.get(i).getModelSeguradora().getTelefone(),
                lista.get(i).getModelSeguradora().getCelular(),
                lista.get(i).getModelSeguradora().getEmail(),
                lista.get(i).getModelSeguradora().getObservacao(),});
        }
    }

    private void SetIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ictrol.png")));
    }
}
