/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerServicos;
import Model.ModelServicos;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import util.Exporter;
import util.Moeda;

/**
 *
 * @author studiomicroweb
 */
public class ViewCobertura extends javax.swing.JFrame {

    ModelServicos modelServicos = new ModelServicos();
    ControllerServicos controllerServicos = new ControllerServicos();
    ArrayList<ModelServicos> listamModelServicos = new ArrayList<ModelServicos>();

    /**
     * Creates new form ViewServico
     */
    public ViewCobertura() {
        initComponents();
        SetIcone();
        carregarServicos();
        setLocationRelativeTo(null);
    }

    static int codigo = 0;
    static String tipoCadastro = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCobertura().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbServicos = new javax.swing.JTable();
        jbExportar3 = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(549, 420));
        setPreferredSize(new java.awt.Dimension(549, 440));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(1002, 390));
        jPanel3.setPreferredSize(new java.awt.Dimension(1002, 390));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btIncluir.setBackground(new java.awt.Color(0, 153, 0));
        btIncluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btIncluir.setForeground(new java.awt.Color(255, 255, 255));
        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_add.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.setMaximumSize(new java.awt.Dimension(120, 25));
        btIncluir.setMinimumSize(new java.awt.Dimension(120, 25));
        btIncluir.setPreferredSize(new java.awt.Dimension(120, 25));
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        jPanel1.add(btIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        btEditar.setBackground(new java.awt.Color(255, 102, 0));
        btEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditar.setForeground(new java.awt.Color(255, 255, 255));
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_edit.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setMaximumSize(new java.awt.Dimension(120, 25));
        btEditar.setMinimumSize(new java.awt.Dimension(120, 25));
        btEditar.setPreferredSize(new java.awt.Dimension(120, 25));
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 30));

        btExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_delete.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setMaximumSize(new java.awt.Dimension(120, 25));
        btExcluir.setMinimumSize(new java.awt.Dimension(120, 25));
        btExcluir.setPreferredSize(new java.awt.Dimension(120, 25));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("COBERTURAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, -1));

        jLabel3.setBackground(new java.awt.Color(251, 251, 251));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cog.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(234, 239, 243));
        kGradientPanel1.setkGradientFocus(-5);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(520, 210));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane6.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(1220, 180));

        tbServicos.setAutoCreateRowSorter(true);
        tbServicos.setBackground(new java.awt.Color(247, 247, 247));
        tbServicos.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Cobertura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbServicos.setGridColor(new java.awt.Color(247, 247, 247));
        tbServicos.setMinimumSize(new java.awt.Dimension(610, 0));
        tbServicos.setRowHeight(20);
        tbServicos.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbServicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tbServicos);
        if (tbServicos.getColumnModel().getColumnCount() > 0) {
            tbServicos.getColumnModel().getColumn(0).setMinWidth(80);
            tbServicos.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbServicos.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        kGradientPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 460, 200));

        jbExportar3.setBackground(new java.awt.Color(0, 153, 0));
        jbExportar3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExportar3.setForeground(new java.awt.Color(255, 255, 255));
        jbExportar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/excel.png"))); // NOI18N
        jbExportar3.setText("EXPORTAR");
        jbExportar3.setPreferredSize(new java.awt.Dimension(140, 35));
        jbExportar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExportar3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jbExportar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 550, 270));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(234, 239, 243));
        kGradientPanel2.setkGradientFocus(0);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 70));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        // TODO add your handling code here:
        tipoCadastro = "novo";
        new ViewCadCobertura().setVisible(true);
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        //Alterar 
        tipoCadastro = "alteracao";
        int linha = tbServicos.getSelectedRow();
        String nome = (String) tbServicos.getValueAt(linha, 1);
        codigo = (int) tbServicos.getValueAt(linha, 0);

        modelServicos = controllerServicos.getServicosController(codigo);
        if (modelServicos != null) {
            new ViewCadCobertura().setVisible(true);
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int linha = tbServicos.getSelectedRow();
        String nome = (String) tbServicos.getValueAt(linha, 1);
        int codigo = (Integer) tbServicos.getValueAt(linha, 0);

        //Pergunta se realmente deseja exclir
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja "
                + "excluir o registro:\n " + "\n" + nome + "?", "Atenção", JOptionPane.YES_NO_OPTION);
        // se sim exclui, se nao nao faz nada
        if (opcao == JOptionPane.OK_OPTION) {
            if (controllerServicos.excluirServicosController(codigo)) {
                JOptionPane.showMessageDialog(this, "Registro excluido com sucesso!");
                carregarServicos();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao e os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        carregarServicos();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jbExportar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExportar3ActionPerformed

        if (tbServicos.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List<JTable> tb = new ArrayList<JTable>();
                List<String> nom = new ArrayList<String>();
                tb.add(tbServicos);
                nom.add("Pessoas");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Os dados foram exportados com sucesso!", "ARQUIVO EXCEL", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro Exception" + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há dados para exportar na tabela", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExportar3ActionPerformed

    public void carregarServicos() {
        listamModelServicos = controllerServicos.getListaServicosController();
        DefaultTableModel modelo = (DefaultTableModel) tbServicos.getModel();
        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listamModelServicos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listamModelServicos.get(i).getCodigo(),
                listamModelServicos.get(i).getNome(),});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbExportar3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTable tbServicos;
    // End of variables declaration//GEN-END:variables

    //carregamento de arquivo após atualizar
    public static ViewCobertura servico;

    private void SetIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ictrol.png")));
    }
}
