/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerCobertura;
import Controller.ControllerFormaPagamento;
import util.Datas;
import Controller.ControllerOp;
import Controller.ControllerSeguradora;
import Controller.ControllerServicos;
import Model.ModelCobertura;
import Model.ModelFormaPagamento;
import Model.ModelOp;
import Model.ModelSeguradora;
import Model.ModelServicos;
import conexao.ConexaoBanco;
import java.sql.Connection;
import util.Mascaras;
import util.Moeda;
import Controller.ControllerCidade;
import Controller.ControllerFuncionario;
import Controller.ControllerEstado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;

/**
 *
 * @author Administrador
 */
public final class ViewOpDeletados extends javax.swing.JFrame {

    Mascaras Mascaras = new Mascaras();
    ModelServicos modelServicos = new ModelServicos();
    ArrayList<ModelServicos> listaModelServicos = new ArrayList<>();
    ControllerServicos controllerServicos = new ControllerServicos();
    ArrayList<ModelOp> listaModelOp = new ArrayList<>();

    ControllerOp controllerOp = new ControllerOp();
    ArrayList<ModelOp> listaModelOpAlterar = new ArrayList<>();
    ModelOp modelOp = new ModelOp();
    ArrayList<ModelSeguradora> listaModelSeguradora = new ArrayList<>();
    ControllerSeguradora controllerSeguradora = new ControllerSeguradora();
    ModelSeguradora modelSeguradora = new ModelSeguradora();
    ControllerEstado controllerEstado = new ControllerEstado();
    ControllerCidade controllerCidade = new ControllerCidade();
    ControllerFormaPagamento controllerTipoPagamento = new ControllerFormaPagamento();
    ArrayList<ModelFormaPagamento> listaModelTipoPagamentos = new ArrayList<>();
    float valorCartao, valorCheque, valorDinheiro, valorVale;
    ControllerFuncionario controllerFuncionario = new ControllerFuncionario();
    ControllerCobertura controllerCobertura = new ControllerCobertura();
    ArrayList<ModelCobertura> listaModelCobertura = new ArrayList<>();
    ModelFormaPagamento modelFormaPagamento = new ModelFormaPagamento();

    public ViewOpDeletados() {
        initComponents();
        SetIcone();
        this.carregarProcessosDeletados();
        jTabbedPanelDespesas.setSelectedIndex(0);
    }
    static int codigo = 0;
    static String tipoCadastro = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadOcupacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOpDeletados().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel15 = new keeptoo.KGradientPanel();
        kButtonPendentes1 = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPanelDespesas = new javax.swing.JTabbedPane();
        AguardandoPagamento = new javax.swing.JPanel();
        kGradientPanel12 = new keeptoo.KGradientPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbProcessosAndamento = new javax.swing.JTable();
        kGradientPanel11 = new keeptoo.KGradientPanel();
        btBuscarAndamento = new javax.swing.JButton();
        tfPesquisarAndamento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btLimparAndamento = new javax.swing.JButton();
        jpRevorgarConta1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbBuscarAndamento = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROCESSOS DELETADOS");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1085, 614));
        setPreferredSize(new java.awt.Dimension(1085, 614));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel15.setBackground(new java.awt.Color(146, 171, 197));
        kGradientPanel15.setkBorderRadius(0);
        kGradientPanel15.setkEndColor(new java.awt.Color(146, 171, 197));
        kGradientPanel15.setkGradientFocus(0);
        kGradientPanel15.setkStartColor(new java.awt.Color(146, 171, 197));
        kGradientPanel15.setName(""); // NOI18N
        kGradientPanel15.setPreferredSize(new java.awt.Dimension(1300, 40));

        kButtonPendentes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/Refresh.png"))); // NOI18N
        kButtonPendentes1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        kButtonPendentes1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        kButtonPendentes1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButtonPendentes1.setIconTextGap(20);
        kButtonPendentes1.setkAllowGradient(false);
        kButtonPendentes1.setkAllowTab(false);
        kButtonPendentes1.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButtonPendentes1.setkBorderRadius(0);
        kButtonPendentes1.setkEndColor(new java.awt.Color(234, 239, 243));
        kButtonPendentes1.setkForeGround(new java.awt.Color(51, 51, 51));
        kButtonPendentes1.setkHoverEndColor(new java.awt.Color(234, 239, 243));
        kButtonPendentes1.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        kButtonPendentes1.setkHoverStartColor(new java.awt.Color(234, 239, 243));
        kButtonPendentes1.setkPressedColor(new java.awt.Color(234, 239, 243));
        kButtonPendentes1.setkSelectedColor(new java.awt.Color(197, 201, 206));
        kButtonPendentes1.setkStartColor(new java.awt.Color(255, 255, 255));
        kButtonPendentes1.setPreferredSize(new java.awt.Dimension(60, 40));
        kButtonPendentes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonPendentes1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("PROCESSOS DELETADOS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/full-trash.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout kGradientPanel15Layout = new org.jdesktop.layout.GroupLayout(kGradientPanel15);
        kGradientPanel15.setLayout(kGradientPanel15Layout);
        kGradientPanel15Layout.setHorizontalGroup(
            kGradientPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(kGradientPanel15Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 285, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 664, Short.MAX_VALUE)
                .add(kButtonPendentes1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel15Layout.setVerticalGroup(
            kGradientPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
            .add(kGradientPanel15Layout.createSequentialGroup()
                .add(2, 2, 2)
                .add(kButtonPendentes1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(org.jdesktop.layout.GroupLayout.LEADING, kGradientPanel15Layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(kGradientPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)))
        );

        getContentPane().add(kGradientPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1085, -1));

        jTabbedPanelDespesas.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanelDespesas.setFocusable(false);
        jTabbedPanelDespesas.setMaximumSize(new java.awt.Dimension(1084, 730));
        jTabbedPanelDespesas.setMinimumSize(new java.awt.Dimension(1084, 730));
        jTabbedPanelDespesas.setPreferredSize(new java.awt.Dimension(1084, 730));

        AguardandoPagamento.setBackground(new java.awt.Color(255, 255, 255));
        AguardandoPagamento.setMaximumSize(new java.awt.Dimension(1084, 575));
        AguardandoPagamento.setMinimumSize(new java.awt.Dimension(1084, 575));
        AguardandoPagamento.setPreferredSize(new java.awt.Dimension(1084, 575));

        kGradientPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Processos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        kGradientPanel12.setkBorderRadius(0);
        kGradientPanel12.setkEndColor(new java.awt.Color(234, 239, 243));
        kGradientPanel12.setkGradientFocus(0);
        kGradientPanel12.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel12.setPreferredSize(new java.awt.Dimension(1080, 450));
        kGradientPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane7.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane7.setPreferredSize(new java.awt.Dimension(1220, 180));

        tbProcessosAndamento.setBackground(new java.awt.Color(247, 247, 247));
        tbProcessosAndamento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbProcessosAndamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Seguradora", "CNPJ", "Data Entrada", "Nº Sinistro", "Honorário", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProcessosAndamento.setGridColor(new java.awt.Color(247, 247, 247));
        tbProcessosAndamento.setMinimumSize(new java.awt.Dimension(610, 0));
        tbProcessosAndamento.setRowHeight(20);
        tbProcessosAndamento.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbProcessosAndamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(tbProcessosAndamento);
        if (tbProcessosAndamento.getColumnModel().getColumnCount() > 0) {
            tbProcessosAndamento.getColumnModel().getColumn(0).setMinWidth(80);
            tbProcessosAndamento.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbProcessosAndamento.getColumnModel().getColumn(0).setMaxWidth(80);
            tbProcessosAndamento.getColumnModel().getColumn(2).setMinWidth(150);
            tbProcessosAndamento.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbProcessosAndamento.getColumnModel().getColumn(2).setMaxWidth(150);
            tbProcessosAndamento.getColumnModel().getColumn(3).setMinWidth(100);
            tbProcessosAndamento.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbProcessosAndamento.getColumnModel().getColumn(3).setMaxWidth(100);
            tbProcessosAndamento.getColumnModel().getColumn(4).setMinWidth(120);
            tbProcessosAndamento.getColumnModel().getColumn(4).setPreferredWidth(120);
            tbProcessosAndamento.getColumnModel().getColumn(4).setMaxWidth(120);
            tbProcessosAndamento.getColumnModel().getColumn(5).setMinWidth(120);
            tbProcessosAndamento.getColumnModel().getColumn(5).setPreferredWidth(120);
            tbProcessosAndamento.getColumnModel().getColumn(5).setMaxWidth(120);
            tbProcessosAndamento.getColumnModel().getColumn(6).setMinWidth(150);
            tbProcessosAndamento.getColumnModel().getColumn(6).setPreferredWidth(150);
            tbProcessosAndamento.getColumnModel().getColumn(6).setMaxWidth(150);
        }

        kGradientPanel12.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1010, 400));

        AguardandoPagamento.add(kGradientPanel12);

        kGradientPanel11.setkBorderRadius(0);
        kGradientPanel11.setkEndColor(new java.awt.Color(234, 239, 243));
        kGradientPanel11.setkGradientFocus(0);
        kGradientPanel11.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel11.setPreferredSize(new java.awt.Dimension(1080, 110));
        kGradientPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btBuscarAndamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/View.png"))); // NOI18N
        btBuscarAndamento.setPreferredSize(new java.awt.Dimension(50, 40));
        btBuscarAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarAndamentoActionPerformed(evt);
            }
        });
        kGradientPanel11.add(btBuscarAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 50, 40));

        tfPesquisarAndamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPesquisarAndamentoKeyPressed(evt);
            }
        });
        kGradientPanel11.add(tfPesquisarAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 110, 28));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("BUSCAR:");
        kGradientPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        btLimparAndamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Erase.png"))); // NOI18N
        btLimparAndamento.setText("LIMPAR FILTRO");
        btLimparAndamento.setPreferredSize(new java.awt.Dimension(50, 40));
        btLimparAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparAndamentoActionPerformed(evt);
            }
        });
        kGradientPanel11.add(btLimparAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 180, -1));

        jpRevorgarConta1.setBackground(new java.awt.Color(255, 102, 0));
        jpRevorgarConta1.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jpRevorgarConta1.setForeground(new java.awt.Color(255, 255, 255));
        jpRevorgarConta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Back.png"))); // NOI18N
        jpRevorgarConta1.setText("REABRIR PROCESSO");
        jpRevorgarConta1.setPreferredSize(new java.awt.Dimension(180, 40));
        jpRevorgarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpRevorgarConta1ActionPerformed(evt);
            }
        });
        kGradientPanel11.add(jpRevorgarConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("BUSCAR POR:");
        kGradientPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 100, -1));

        cbBuscarAndamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Sinistro" }));
        cbBuscarAndamento.setPreferredSize(new java.awt.Dimension(120, 28));
        kGradientPanel11.add(cbBuscarAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, 28));

        AguardandoPagamento.add(kGradientPanel11);

        jTabbedPanelDespesas.addTab("PROCESSOS AGUARDANDO PAGAMENTO", AguardandoPagamento);

        getContentPane().add(jTabbedPanelDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 1085, 590));

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarFechar1ActionPerformed
        // habilita ou desabilita campos
        dispose();
    }//GEN-LAST:event_btCancelarFechar1ActionPerformed

    private void cbTipoDespesaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbTipoDespesaPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDespesaPopupMenuWillBecomeInvisible

    private void kButtonPendentes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonPendentes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButtonPendentes1ActionPerformed

    private void btBuscarAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarAndamentoActionPerformed
        // TODO add your handling code here:
        int situacao = 0;
        String seleciona = "";
        String conteudo = tfPesquisarAndamento.getText();
        int i = cbBuscarAndamento.getSelectedIndex();
        switch (i) {
            case 0:
                seleciona = "ordem_processo.codigo";
                break;
            case 1:
                seleciona = "ordem_processo.NumeroSinistro";
                break;
            default:
                System.out.println("Não selecionado");
                break;
        }
        try {
            listaModelOp = controllerOp.getListaOpControllerBusca(seleciona, conteudo, situacao);
            pesquisaAndamento(listaModelOp);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nenhum processo encontrado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarAndamentoActionPerformed

    private void pesquisaAndamento(ArrayList<ModelOp> lista) {

        DefaultTableModel modelo = (DefaultTableModel) tbProcessosAndamento.getModel();
        modelo.setNumRows(0);

        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = lista.size();
        for (int i = 0; i < cont; i++) {
            String Seguradora = controllerSeguradora.getSeguradoraController(lista.get(i).getSeguradoras()).getNome();
            String CNPJ = controllerSeguradora.getSeguradoraController(lista.get(i).getSeguradoras()).getCnpj();
            String Situacao = controllerTipoPagamento.getFormaPagamentoController(lista.get(i).getTipo()).getDescricao();
            modelo.addRow(new Object[]{
                lista.get(i).getCodigo(),
                Seguradora,
                CNPJ,
                (new Mascaras().DataRecuperasql(lista.get(i).getDataEntrada())),
                lista.get(i).getNumeroSinistro(),
                (new Moeda().valorStringTODoubleAtt(lista.get(i).getValorTotalHonorariosSemRetencao().toString())),
                Situacao
            });
        }
    }

    private void btLimparAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparAndamentoActionPerformed
        // TODO add your handling code here:
        this.tbProcessosAndamento.setRowSorter(null);
        tfPesquisarAndamento.setText("");
    }//GEN-LAST:event_btLimparAndamentoActionPerformed

    private void jpRevorgarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpRevorgarConta1ActionPerformed
        // TODO add your handling code here:
        modelOp = new ModelOp();
        try {
            int linha = tbProcessosAndamento.getSelectedRow();
            int ViewOpcodigo = (int) tbProcessosAndamento.getValueAt(linha, 0);
            Datas bl = new Datas();

            modelOp.setCodigo(ViewOpcodigo);
            modelOp.setTipo(1);
            modelOp.setTipoPagamento(0);

            //pegunta
            int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja"
                    + " REABRIR O PROCESSO DE Nº:\n" + "\n " + ViewOpcodigo + "?", "Atenção", JOptionPane.YES_NO_OPTION);
            //se sim revoga, se não não faz nada
            if (opcao == JOptionPane.OK_OPTION) {
                if (controllerOp.pagarReceberProcessoController(modelOp)) {
                    JOptionPane.showMessageDialog(this, "Processo Reaberto!");
                    carregarProcessosDeletados();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um processo!", "ATENÇÂO", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jpRevorgarConta1ActionPerformed

    private void tfPesquisarAndamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisarAndamentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            int situacao = 0;
            String seleciona = "";
            String conteudo = tfPesquisarAndamento.getText();
            int i = cbBuscarAndamento.getSelectedIndex();
            switch (i) {
                case 0:
                    seleciona = "ordem_processo.codigo";
                    break;
                case 1:
                    seleciona = "ordem_processo.NumeroSinistro";
                    break;
                default:
                    System.out.println("Não selecionado");
                    break;
            }
            try {
                listaModelOp = controllerOp.getListaOpControllerBusca(seleciona, conteudo, situacao);
                pesquisaAndamento(listaModelOp);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Nenhum processo encontrado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_tfPesquisarAndamentoKeyPressed

    public void carregarProcessosDeletados() {
        listaModelOp = controllerOp.getProcessosRecebidosController(0);
        DefaultTableModel modelo = (DefaultTableModel) tbProcessosAndamento.getModel();
        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listaModelOp.size();
        for (int i = 0; i < cont; i++) {
            modelSeguradora = controllerSeguradora.getSeguradoraController(listaModelOp.get(i).getSeguradoras());
            //modelFormaPagamento = controllerTipoPagamento.getFormaPagamentoController(listaModelOp.get(i).getTipo());
            modelo.addRow(new Object[]{
                listaModelOp.get(i).getCodigo(),
                modelSeguradora.getNome(),
                modelSeguradora.getCnpj(),
                (new Mascaras().DataRecuperasql(String.valueOf(listaModelOp.get(i).getDataEntrada()))),
                listaModelOp.get(i).getNumeroSinistro(),
                (new Moeda().valorStringTODoubleAtt(listaModelOp.get(i).getValorTotalHonorariosSemRetencao().toString())),
                "Orçamento"
            //modelFormaPagamento.getDescricao()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AguardandoPagamento;
    private javax.swing.JButton btBuscarAndamento;
    private javax.swing.JButton btLimparAndamento;
    private javax.swing.JComboBox<String> cbBuscarAndamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPanelDespesas;
    private javax.swing.JButton jpRevorgarConta1;
    private keeptoo.KButton kButtonPendentes1;
    private keeptoo.KGradientPanel kGradientPanel11;
    private keeptoo.KGradientPanel kGradientPanel12;
    private keeptoo.KGradientPanel kGradientPanel15;
    private javax.swing.JTable tbProcessosAndamento;
    private javax.swing.JTextField tfPesquisarAndamento;
    // End of variables declaration//GEN-END:variables

    public static ViewOpDeletados oPDEL;
    ConexaoBanco cc = new ConexaoBanco();
    Connection cn = cc.conectar();

    private void SetIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ictrol.png")));
    }

}
