/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerFuncionario;
import Controller.ControllerOcupacao;
import Model.ModelFuncionario;
import Model.ModelOcupacao;
import conexao.ConexaoBanco;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import util.Exporter;

/**
 *
 * @author Work
 */
public final class ViewCadUser extends javax.swing.JFrame {

    ModelOcupacao modelOcupacao = new ModelOcupacao();
    ArrayList<ModelOcupacao> listaModelOcupacao = new ArrayList<>();
    ControllerOcupacao controllerOcupacao = new ControllerOcupacao();

    ArrayList<ModelFuncionario> listaModelFuncionarios = new ArrayList<>();
    ControllerFuncionario controllerFuncionarios = new ControllerFuncionario();
    ModelFuncionario modelFuncionarios = new ModelFuncionario();

    /**
     * Creates new form ViewCadUser
     */
    public ViewCadUser() {
        initComponents();
        SetIcone();
        listarOcupacao();
        carregarUsuarios();
        listarFuncionarios();
    }

    void cancelar() {
        cbOcupacao.setSelectedIndex(0);
        cbNome.setSelectedIndex(0);
        tfLogin.setText(null);
        tfSenha.setText(null);
        tfCodigo.setText("Novo");
        btSalvar.setEnabled(true);
        btAtualizar.setEnabled(false);
        btCancelar.setEnabled(false);
    }

    private void listarOcupacao() {
        listaModelOcupacao = controllerOcupacao.getListaOcupacaoController();
        cbOcupacao.removeAllItems();
        for (int i = 0; i < listaModelOcupacao.size(); i++) {
            cbOcupacao.addItem(listaModelOcupacao.get(i).getOcup_descricao());
        }
    }

    private void listarFuncionarios() {
        listaModelFuncionarios = controllerFuncionarios.getListaFuncionarioController();
        cbNome.removeAllItems();
        for (int i = 0; i < listaModelFuncionarios.size(); i++) {
            cbNome.addItem(listaModelFuncionarios.get(i).getNome());
        }
    }

    void limparCamposBanco() {
        tfLogin.setText("");
        tfSenha.setText("");
        cbNome.setSelectedIndex(0);
        cbOcupacao.setSelectedIndex(0);
    }

    void carregarUsuarios() {
        if ((int) tbUsuarios.getRowCount() > 0) {
            DefaultTableModel modelo = (DefaultTableModel) tbUsuarios.getModel();
            modelo.setNumRows(0);
        }
        try {
            DefaultTableModel model = (DefaultTableModel) tbUsuarios.getModel();
            int codigo = 0;
            if (!"Novo".equals(tfCodigo.getText())) {
                codigo = (Integer.parseInt(tfCodigo.getText()));
            }

            String consultar = "SELECT * FROM tbl_usuario";
            String[] datos = new String[5];
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(consultar);
            while (rs.next()) {
                datos[0] = rs.getString("pk_codigo");
                int codOcupacao = (Integer.parseInt(rs.getString("permissao")));
                String NomePermissao = (controllerOcupacao.getOcupacaoControllerCod(codOcupacao).getOcup_descricao());
                datos[1] = NomePermissao;
                datos[2] = rs.getString("nome");
                datos[3] = rs.getString("login");
                datos[4] = rs.getString("senha");

                model.addRow(datos);
            }
            tbUsuarios.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(ViewCadUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGContaBancaria = new keeptoo.KGradientPanel();
        cbOcupacao = new javax.swing.JComboBox<String>();
        jLBanco = new javax.swing.JLabel();
        jLBancoConta = new javax.swing.JLabel();
        jLBancoAgencia = new javax.swing.JLabel();
        jLBancoObs = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        tfLogin = new javax.swing.JTextField();
        tfSenha = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        tfCodigo = new javax.swing.JTextField();
        jbExportar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        kGradientPanel15 = new keeptoo.KGradientPanel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        kGradientPanel13 = new keeptoo.KGradientPanel();
        kGradientPanel23 = new keeptoo.KGradientPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbNome = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(990, 430));
        setPreferredSize(new java.awt.Dimension(990, 430));
        setResizable(false);

        kGContaBancaria.setkBorderRadius(0);
        kGContaBancaria.setkEndColor(new java.awt.Color(234, 239, 243));
        kGContaBancaria.setkGradientFocus(0);
        kGContaBancaria.setkStartColor(new java.awt.Color(255, 255, 255));
        kGContaBancaria.setPreferredSize(new java.awt.Dimension(990, 250));
        kGContaBancaria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbOcupacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<selecione>" }));
        cbOcupacao.setSelectedIndex(-1);
        cbOcupacao.setMinimumSize(new java.awt.Dimension(85, 25));
        cbOcupacao.setPreferredSize(new java.awt.Dimension(85, 25));
        cbOcupacao.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbOcupacaoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        kGContaBancaria.add(cbOcupacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, -1));

        jLBanco.setText("Permissão (por Ocupação)");
        kGContaBancaria.add(jLBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));

        jLBancoConta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLBancoConta.setText("Login");
        kGContaBancaria.add(jLBancoConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 90, -1));

        jLBancoAgencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLBancoAgencia.setText("Senha");
        kGContaBancaria.add(jLBancoAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 90, -1));

        jLBancoObs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLBancoObs.setText("Nome:");
        kGContaBancaria.add(jLBancoObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 120, -1));

        jScrollPane6.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(1170, 170));

        tbUsuarios.setBackground(new java.awt.Color(247, 247, 247));
        tbUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Permissão", "Nome", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.setGridColor(new java.awt.Color(247, 247, 247));
        tbUsuarios.setMinimumSize(new java.awt.Dimension(610, 0));
        tbUsuarios.setRowHeight(20);
        tbUsuarios.setSelectionBackground(new java.awt.Color(0, 153, 0));
        tbUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tbUsuarios);
        if (tbUsuarios.getColumnModel().getColumnCount() > 0) {
            tbUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
            tbUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
            tbUsuarios.getColumnModel().getColumn(1).setMinWidth(150);
            tbUsuarios.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbUsuarios.getColumnModel().getColumn(1).setMaxWidth(150);
            tbUsuarios.getColumnModel().getColumn(3).setMinWidth(150);
            tbUsuarios.getColumnModel().getColumn(3).setPreferredWidth(150);
            tbUsuarios.getColumnModel().getColumn(3).setMaxWidth(150);
            tbUsuarios.getColumnModel().getColumn(4).setMinWidth(150);
            tbUsuarios.getColumnModel().getColumn(4).setPreferredWidth(150);
            tbUsuarios.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        kGContaBancaria.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 900, 180));

        tfLogin.setPreferredSize(new java.awt.Dimension(150, 28));
        tfLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLoginFocusLost(evt);
            }
        });
        kGContaBancaria.add(tfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        tfSenha.setPreferredSize(new java.awt.Dimension(150, 28));
        tfSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSenhaFocusLost(evt);
            }
        });
        kGContaBancaria.add(tfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        btSalvar.setBackground(new java.awt.Color(0, 153, 0));
        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/disk.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setPreferredSize(new java.awt.Dimension(140, 35));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        kGContaBancaria.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        btExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/clear.png"))); // NOI18N
        btExcluir.setMaximumSize(new java.awt.Dimension(60, 40));
        btExcluir.setMinimumSize(new java.awt.Dimension(60, 40));
        btExcluir.setPreferredSize(new java.awt.Dimension(60, 40));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        kGContaBancaria.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, -1, -1));

        btAlterar.setBackground(new java.awt.Color(0, 102, 255));
        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_edit.png"))); // NOI18N
        btAlterar.setMaximumSize(new java.awt.Dimension(60, 40));
        btAlterar.setMinimumSize(new java.awt.Dimension(60, 40));
        btAlterar.setPreferredSize(new java.awt.Dimension(60, 40));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        kGContaBancaria.add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        btAtualizar.setBackground(new java.awt.Color(56, 178, 255));
        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/page_refresh.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);
        btAtualizar.setPreferredSize(new java.awt.Dimension(140, 35));
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        kGContaBancaria.add(btAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        tfCodigo.setEditable(false);
        tfCodigo.setBackground(new java.awt.Color(153, 0, 51));
        tfCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfCodigo.setForeground(new java.awt.Color(255, 255, 255));
        tfCodigo.setText("Novo");
        tfCodigo.setPreferredSize(new java.awt.Dimension(100, 35));
        kGContaBancaria.add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jbExportar.setBackground(new java.awt.Color(0, 153, 0));
        jbExportar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExportar.setForeground(new java.awt.Color(255, 255, 255));
        jbExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/excel.png"))); // NOI18N
        jbExportar.setText("EXPORTAR");
        jbExportar.setPreferredSize(new java.awt.Dimension(140, 35));
        jbExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExportarActionPerformed(evt);
            }
        });
        kGContaBancaria.add(jbExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        btCancelar.setBackground(new java.awt.Color(56, 178, 255));
        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/abort.png"))); // NOI18N
        btCancelar.setEnabled(false);
        btCancelar.setMaximumSize(new java.awt.Dimension(60, 40));
        btCancelar.setMinimumSize(new java.awt.Dimension(60, 40));
        btCancelar.setPreferredSize(new java.awt.Dimension(60, 40));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        kGContaBancaria.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        kGradientPanel15.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel15.setkBorderRadius(0);
        kGradientPanel15.setkEndColor(new java.awt.Color(146, 171, 197));
        kGradientPanel15.setkStartColor(new java.awt.Color(146, 171, 197));
        kGradientPanel15.setName(""); // NOI18N
        kGradientPanel15.setPreferredSize(new java.awt.Dimension(1300, 40));

        kGradientPanel7.setkBorderRadius(0);
        kGradientPanel7.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel7.setkGradientFocus(125);
        kGradientPanel7.setkStartColor(new java.awt.Color(234, 239, 243));

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        kGradientPanel13.setkBorderRadius(0);
        kGradientPanel13.setkEndColor(new java.awt.Color(234, 239, 243));
        kGradientPanel13.setkGradientFocus(250);
        kGradientPanel13.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel13Layout = new javax.swing.GroupLayout(kGradientPanel13);
        kGradientPanel13.setLayout(kGradientPanel13Layout);
        kGradientPanel13Layout.setHorizontalGroup(
            kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        kGradientPanel13Layout.setVerticalGroup(
            kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        kGradientPanel23.setkBorderRadius(0);
        kGradientPanel23.setkEndColor(new java.awt.Color(146, 171, 197));
        kGradientPanel23.setkGradientFocus(125);
        kGradientPanel23.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 102));
        jLabel29.setText("Cadastrar Usuários");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/group_add.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel23Layout = new javax.swing.GroupLayout(kGradientPanel23);
        kGradientPanel23.setLayout(kGradientPanel23Layout);
        kGradientPanel23Layout.setHorizontalGroup(
            kGradientPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        kGradientPanel23Layout.setVerticalGroup(
            kGradientPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel23Layout.createSequentialGroup()
                .addGroup(kGradientPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout kGradientPanel15Layout = new javax.swing.GroupLayout(kGradientPanel15);
        kGradientPanel15.setLayout(kGradientPanel15Layout);
        kGradientPanel15Layout.setHorizontalGroup(
            kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel15Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kGradientPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel15Layout.createSequentialGroup()
                .addComponent(kGradientPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel15Layout.setVerticalGroup(
            kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel15Layout.createSequentialGroup()
                .addComponent(kGradientPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        kGContaBancaria.add(kGradientPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 50));

        cbNome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kGContaBancaria.add(cbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 240, 30));

        getContentPane().add(kGContaBancaria, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbOcupacaoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbOcupacaoPopupMenuWillBecomeInvisible
        // Listar bancos do SQL
        if (this.cbOcupacao.isPopupVisible() && this.cbOcupacao.getSelectedItem() != null) {
            modelOcupacao = controllerOcupacao.getOcupacaoControllerNome(cbOcupacao.getSelectedItem().toString());
            //recupera o nome
            cbOcupacao.setSelectedItem(cbOcupacao.getSelectedItem());
        }
    }//GEN-LAST:event_cbOcupacaoPopupMenuWillBecomeInvisible

    private void tfLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLoginFocusLost
        // CONTA BANCO
        this.tfLogin.setText(tfLogin.getText());
    }//GEN-LAST:event_tfLoginFocusLost

    private void tfSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSenhaFocusLost
        // AGENCIA
        this.tfSenha.setText(tfSenha.getText());
    }//GEN-LAST:event_tfSenhaFocusLost

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if ((cbNome.getSelectedIndex() < 0) || (tfLogin.getText().equals("")) || (tfSenha.getText().equals("")) || cbOcupacao.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            modelOcupacao = controllerOcupacao.getOcupacaoControllerNome(cbOcupacao.getSelectedItem().toString());
            int codigoOcupacao = 0;
            codigoOcupacao = controllerOcupacao.getOcupacaoControllerNome(this.cbOcupacao.getSelectedItem().toString()).getCodigo();

            String insertar = "INSERT INTO tbl_usuario(permissao,nome,login,senha) VALUES (?,?,?,?)";
            try {
                // variável para obter o número de bytes de uma imagem.
                PreparedStatement pst = cn.prepareStatement(insertar);
                pst.setInt(1, codigoOcupacao);
                pst.setString(2, cbNome.getSelectedItem().toString());
                pst.setString(3, tfLogin.getText());
                pst.setString(4, tfSenha.getText());

                int i = pst.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!");
                }
                carregarUsuarios();
                limparCamposBanco();
            } catch (SQLException ex) {
                Logger.getLogger(ViewCadUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int fila = tbUsuarios.getSelectedRow();
        if (fila > -1) {
            String cod = tbUsuarios.getValueAt(fila, 0).toString();
            String sqlElim = "DELETE FROM tbl_usuario WHERE pk_codigo='" + cod + "'";
            try {
                PreparedStatement pst = cn.prepareStatement(sqlElim);
                int n = pst.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário apagado com sucesso!");
                    carregarUsuarios();

                } else {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro ao apagar usuário");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ViewCadUser.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        int fila = tbUsuarios.getSelectedRow();
        if (fila >= 0) {
            btSalvar.setEnabled(false);
            btAtualizar.setEnabled(true);
            btCancelar.setEnabled(true);
            String cod = tbUsuarios.getValueAt(fila, 0).toString();
            String ocupacao = tbUsuarios.getValueAt(fila, 1).toString();
            String nome = tbUsuarios.getValueAt(fila, 2).toString();
            String login = tbUsuarios.getValueAt(fila, 3).toString();
            String senha = tbUsuarios.getValueAt(fila, 4).toString();
            tfCodigo.setText(cod);
            cbOcupacao.setSelectedItem(controllerOcupacao.getOcupacaoControllerNome(ocupacao).getOcup_descricao());
            tfLogin.setText(login);
            tfSenha.setText(senha);
            cbNome.setSelectedItem(nome);
        } else {
            JOptionPane.showMessageDialog(null, "Escolha uma linha na tabela antes!");
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        modelOcupacao = controllerOcupacao.getOcupacaoControllerNome(cbOcupacao.getSelectedItem().toString());
        int codigoOcupacao = 0;
        codigoOcupacao = controllerOcupacao.getOcupacaoControllerNome(this.cbOcupacao.getSelectedItem().toString()).getCodigo();
        int cod = 0;
        cod = (Integer.parseInt(tfCodigo.getText()));
        System.out.print(cod);
        System.out.print(codigoOcupacao);
        try {
            FileInputStream archivofoto;
            String sql = "UPDATE tbl_usuario SET pk_codigo = ?, "
                    + "permissao = ?,"
                    + "nome = ?,"
                    + "login = ?,"
                    + "senha = ?"
                    + "WHERE pk_codigo = '" + tfCodigo.getText() + "'";

            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, tfCodigo.getText());
            pst.setInt(2, codigoOcupacao);
            pst.setString(3, cbNome.getSelectedItem().toString());
            pst.setString(4, tfLogin.getText());
            pst.setString(5, tfSenha.getText());

            int n = pst.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso!");
                btSalvar.setEnabled(true);
                btAtualizar.setEnabled(false);
                carregarUsuarios();
                cancelar();
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao atualizar usuário");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewCadUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void jbExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExportarActionPerformed

        if (tbUsuarios.getRowCount() > 0) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List<JTable> tb = new ArrayList<JTable>();
                List<String> nom = new ArrayList<String>();
                tb.add(tbUsuarios);
                nom.add("Pessoas");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exporter e = new Exporter(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Os dados foram exportados com sucesso!", "ARQUIVO EXCEL", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro Exception" + e.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há dados para exportar na tabela", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExportarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        cancelar();
        carregarUsuarios();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbNome;
    private javax.swing.JComboBox<String> cbOcupacao;
    private javax.swing.JLabel jLBanco;
    private javax.swing.JLabel jLBancoAgencia;
    private javax.swing.JLabel jLBancoConta;
    private javax.swing.JLabel jLBancoObs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbExportar;
    private keeptoo.KGradientPanel kGContaBancaria;
    private keeptoo.KGradientPanel kGradientPanel13;
    private keeptoo.KGradientPanel kGradientPanel15;
    private keeptoo.KGradientPanel kGradientPanel23;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables

    ConexaoBanco cc = new ConexaoBanco();
    Connection cn = cc.conectar();

    private void SetIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ictrol.png")));
    }
}
