/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerUsuario;
import javax.swing.JOptionPane;
import Model.ModelSessaoUsuario;
import Model.ModelUsuario;
import static View.ViewCidade.cidade;
import static View.ViewPrincipal.principal;
import static View.ViewContasPagar.contasPagar;
import static View.ViewCobertura.servico;
import javax.swing.UIManager;
import static View.ViewFuncionario.Funcionario;
import static View.ViewSeguradora.seguradora;
import static View.ViewFluxoDados.fluxodados;
import java.awt.Toolkit;
import static View.ViewOp.op;
import javax.swing.UnsupportedLookAndFeelException;
import static View.ViewDespesasAgentes.viewdespesasagentes;
import static View.ViewFluxoContasDespesas.viewfluxocontasdespesas;
import static View.ViewContasReceber.viewcontasreceber;

/**
 *
 * @author studiomicroweb
 */
public class ViewLogin extends javax.swing.JFrame {

    private final ModelSessaoUsuario modelSessaoUsuario = new ModelSessaoUsuario();

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
        SetIcone();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel23 = new keeptoo.KGradientPanel();
        btnAcesso = new javax.swing.JButton();
        tfSenha = new javax.swing.JPasswordField();
        tfUsuario = new javax.swing.JTextField();
        uJPanelImagem7 = new componentes.UJPanelImagem();
        uJPanelImagem6 = new componentes.UJPanelImagem();
        kGLogin = new keeptoo.KGradientPanel();
        uJPanelImagem2 = new componentes.UJPanelImagem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(450, 340));
        setPreferredSize(new java.awt.Dimension(450, 340));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel23.setkBorderRadius(0);
        kGradientPanel23.setkEndColor(new java.awt.Color(146, 171, 197));
        kGradientPanel23.setkGradientFocus(0);
        kGradientPanel23.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel23.setPreferredSize(new java.awt.Dimension(460, 170));

        btnAcesso.setBackground(new java.awt.Color(0, 153, 0));
        btnAcesso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAcesso.setForeground(new java.awt.Color(255, 255, 255));
        btnAcesso.setText("ENTRAR");
        btnAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessoActionPerformed(evt);
            }
        });

        tfSenha.setFont(new java.awt.Font("Humnst777 Blk BT", 1, 14)); // NOI18N
        tfSenha.setForeground(new java.awt.Color(102, 102, 102));
        tfSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        tfSenha.setCaretColor(new java.awt.Color(153, 153, 153));
        tfSenha.setMinimumSize(new java.awt.Dimension(200, 30));
        tfSenha.setPreferredSize(new java.awt.Dimension(200, 30));
        tfSenha.setSelectionColor(new java.awt.Color(51, 51, 51));
        tfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSenhaActionPerformed(evt);
            }
        });

        tfUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfUsuario.setForeground(new java.awt.Color(102, 102, 102));
        tfUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        tfUsuario.setCaretColor(new java.awt.Color(153, 153, 153));
        tfUsuario.setMinimumSize(new java.awt.Dimension(200, 30));
        tfUsuario.setPreferredSize(new java.awt.Dimension(200, 30));
        tfUsuario.setSelectionColor(new java.awt.Color(51, 51, 51));

        uJPanelImagem7.setImagem(new java.io.File("C:\\Sistema\\src\\imagens\\user-login.png"));
        uJPanelImagem7.setMinimumSize(new java.awt.Dimension(50, 40));
        uJPanelImagem7.setPreferredSize(new java.awt.Dimension(50, 40));
        uJPanelImagem7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uJPanelImagem6.setImagem(new java.io.File("C:\\Sistema\\src\\imagens\\pw-login.png"));
        uJPanelImagem6.setMinimumSize(new java.awt.Dimension(50, 40));
        uJPanelImagem6.setPreferredSize(new java.awt.Dimension(50, 40));
        uJPanelImagem6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.layout.GroupLayout kGradientPanel23Layout = new org.jdesktop.layout.GroupLayout(kGradientPanel23);
        kGradientPanel23.setLayout(kGradientPanel23Layout);
        kGradientPanel23Layout.setHorizontalGroup(
            kGradientPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, kGradientPanel23Layout.createSequentialGroup()
                .add(50, 50, 50)
                .add(kGradientPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(kGradientPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(kGradientPanel23Layout.createSequentialGroup()
                            .add(uJPanelImagem7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(0, 0, 0)
                            .add(tfUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(kGradientPanel23Layout.createSequentialGroup()
                            .add(uJPanelImagem6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(0, 0, 0)
                            .add(tfSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(btnAcesso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(50, 50, 50))
        );
        kGradientPanel23Layout.setVerticalGroup(
            kGradientPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, kGradientPanel23Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(kGradientPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(uJPanelImagem7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(kGradientPanel23Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(tfUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(10, 10, 10)
                .add(kGradientPanel23Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(uJPanelImagem6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(kGradientPanel23Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(tfSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnAcesso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(98, 98, 98))
        );

        getContentPane().add(kGradientPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 460, 170));

        kGLogin.setkBorderRadius(0);
        kGLogin.setkEndColor(new java.awt.Color(234, 239, 243));
        kGLogin.setkGradientFocus(-5);
        kGLogin.setkStartColor(new java.awt.Color(255, 255, 255));
        kGLogin.setPreferredSize(new java.awt.Dimension(520, 210));
        kGLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uJPanelImagem2.setImagem(new java.io.File("C:\\Sistema\\src\\imagens\\login-img.png"));
        uJPanelImagem2.setMinimumSize(new java.awt.Dimension(280, 122));
        uJPanelImagem2.setPreferredSize(new java.awt.Dimension(280, 122));

        org.jdesktop.layout.GroupLayout uJPanelImagem2Layout = new org.jdesktop.layout.GroupLayout(uJPanelImagem2);
        uJPanelImagem2.setLayout(uJPanelImagem2Layout);
        uJPanelImagem2Layout.setHorizontalGroup(
            uJPanelImagem2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 280, Short.MAX_VALUE)
        );
        uJPanelImagem2Layout.setVerticalGroup(
            uJPanelImagem2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 122, Short.MAX_VALUE)
        );

        kGLogin.add(uJPanelImagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        getContentPane().add(kGLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessoActionPerformed
        // TODO add your handling code here:
        autenticar();
    }//GEN-LAST:event_btnAcessoActionPerformed

    private void tfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSenhaActionPerformed
        // TODO add your handling code here:
        autenticar();
    }//GEN-LAST:event_tfSenhaActionPerformed

    private void autenticar() {
        ModelUsuario modelUsuario = new ModelUsuario();
        ControllerUsuario controllerUsuario = new ControllerUsuario();
        modelUsuario.setLogin(this.tfUsuario.getText());
        modelUsuario.setSenha(new String(this.tfSenha.getPassword()));

        if (controllerUsuario.getUsuarioController(modelUsuario)) {
            modelUsuario = controllerUsuario.getUsuarioController(modelUsuario.getLogin());
            modelSessaoUsuario.nome = modelUsuario.getNome();
            modelSessaoUsuario.codigo = modelUsuario.getCodigo();
            modelSessaoUsuario.login = modelUsuario.getLogin();

            ViewPrincipal viewPrincipal = new ViewPrincipal();
            viewPrincipal.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuário/Senha inválida.", "Aviso", JOptionPane.WARNING_MESSAGE);
            //WARNING_MESSAGE
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ViewLogin().setVisible(true);
                principal = new ViewPrincipal();
                cidade = new ViewCidade();
                servico = new ViewCobertura();
                contasPagar = new ViewContasPagar();
                op = new ViewOp();
                Funcionario = new ViewFuncionario();
                seguradora = new ViewSeguradora();
                fluxodados = new ViewFluxoDados();
                viewcontasreceber = new ViewContasReceber();
                viewdespesasagentes = new ViewDespesasAgentes();
                viewfluxocontasdespesas = new ViewFluxoContasDespesas();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcesso;
    private keeptoo.KGradientPanel kGLogin;
    private keeptoo.KGradientPanel kGradientPanel23;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JTextField tfUsuario;
    private componentes.UJPanelImagem uJPanelImagem2;
    private componentes.UJPanelImagem uJPanelImagem6;
    private componentes.UJPanelImagem uJPanelImagem7;
    // End of variables declaration//GEN-END:variables

    public void echo(){
        System.out.println("hello");
    }
    public static ViewLogin login;

    private void SetIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ictrol.png")));
    }

}
